/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AttackPattern {
  constructor(name: string)
  toJson(): string
  getType(): string
}

export declare function testStix(): string

export declare function version(): string
