# STIX 2.1 Type Stubs - simpler version
# Test stubs are sufficient - full validation happens via Rust module import

def parse_timestamp(ts: str) -> str:
    """Parse a STIX timestamp string."""
    ...

def identifier(id_str: str) -> str:
    """Create a STIX identifier from string."""
    ...

def builder(object_type: str) -> "DomainObjectBuilder":
    """Create a builder for the specified SDO type."""
    ...

def to_json(obj: object) -> str:
    """Serialize an object to JSON."""
    ...

def from_json(json_str: str) -> object:
    """Deserialize an object from JSON."""
    ...

def create_version(obj: object) -> object:
    """Create a new version of an object."""
    ...

def get_property(obj: object, name: str) -> object:
    """Get a property from an object."""
    ...

def cyber_builder(object_type: str) -> "CyberObjectBuilder":
    """Create a builder for the specified SCO type."""
    ...

def get_uuid_version(obj: object) -> str:
    """Get UUID version from an object."""
    ...

def relationship_builder() -> "RelationshipBuilder":
    """Create a Relationship builder."""
    ...

def sighting_builder() -> "SightingBuilder":
    """Create a Sighting builder."""
    ...

def marking_builder() -> "MarkingDefinitionBuilder":
    """Create a Marking Definition builder."""
    ...

def extension_builder() -> "ExtensionDefinitionBuilder":
    """Create an Extension Definition builder."""
    ...

def language_content_builder() -> "LanguageContentBuilder":
    """Create a Language Content builder."""
    ...

def bundle_builder() -> "BundleBuilder":
    """Create a Bundle builder."""
    ...

def parse_pattern(pattern: str) -> object:
    """Parse a STIX pattern."""
    ...

def parse_observation(pattern: str) -> object:
    """Parse an observation expression."""
    ...

def parse_qualifier(pattern: str) -> object:
    """Parse a qualifier."""
    ...

def validate_pattern(pattern: str) -> bool:
    """Validate a STIX pattern."""
    ...

def stix_case(value: str) -> str:
    """Convert to STIX kebab-case."""
    ...

def get_object_type(type_str: str) -> str:
    """Get object type from type string."""
    ...

def get_type(identifier: str) -> str:
    """Get type from identifier."""
    ...

def get_uuid(identifier: str) -> str:
    """Get UUID from identifier."""
    ...

def kill_chain_phase(kill_chain_name: str, phase_name: str) -> object:
    """Create a kill chain phase."""
    ...

def hashes() -> "Hashes":
    """Create a Hashes container."""
    ...

class StixError(Exception):
    """Base STIX error type."""

    pass

class DomainObjectBuilder:
    def __init__(self, object_type: str): ...
    def name(self, value: str) -> "DomainObjectBuilder": ...
    def description(self, value: str) -> "DomainObjectBuilder": ...
    def first_seen(self, value: str) -> "DomainObjectBuilder": ...
    def last_seen(self, value: str) -> "DomainObjectBuilder": ...
    def aliases(self, value: list[str]) -> "DomainObjectBuilder": ...
    def kill_chain_phases(self, value: list[object]) -> "DomainObjectBuilder": ...
    def external_references(self, value: list[object]) -> "DomainObjectBuilder": ...
    def sectors(self, value: list[str]) -> "DomainObjectBuilder": ...
    def roles(self, value: list[str]) -> "DomainObjectBuilder": ...
    def identity_class(self, value: str) -> "DomainObjectBuilder": ...
    def pattern(self, value: str) -> "DomainObjectBuilder": ...
    def pattern_type(self, value: str) -> "DomainObjectBuilder": ...
    def pattern_version(self, value: str) -> "DomainObjectBuilder": ...
    def valid_from(self, value: str) -> "DomainObjectBuilder": ...
    def valid_until(self, value: str) -> "DomainObjectBuilder": ...
    def indicator_types(self, value: list[str]) -> "DomainObjectBuilder": ...
    def infrastructure_types(self, value: list[str]) -> "DomainObjectBuilder": ...
    def context(self, value: str) -> "DomainObjectBuilder": ...
    def object_refs(self, value: list[str]) -> "DomainObjectBuilder": ...
    def goals(self, value: list[str]) -> "DomainObjectBuilder": ...
    def resource_level(self, value: str) -> "DomainObjectBuilder": ...
    def primary_motivation(self, value: str) -> "DomainObjectBuilder": ...
    def secondary_motivations(self, value: list[str]) -> "DomainObjectBuilder": ...
    def latitude(self, value: float) -> "DomainObjectBuilder": ...
    def longitude(self, value: float) -> "DomainObjectBuilder": ...
    def precision(self, value: float) -> "DomainObjectBuilder": ...
    def region(self, value: str) -> "DomainObjectBuilder": ...
    def country(self, value: str) -> "DomainObjectBuilder": ...
    def is_family(self, value: bool) -> "DomainObjectBuilder": ...
    def malware_types(self, value: list[str]) -> "DomainObjectBuilder": ...
    def capabilities(self, value: list[str]) -> "DomainObjectBuilder": ...
    def product(self, value: str) -> "DomainObjectBuilder": ...
    def result(self, value: str) -> "DomainObjectBuilder": ...
    def abstract(self, value: str) -> "DomainObjectBuilder": ...
    def content(self, value: str) -> "DomainObjectBuilder": ...
    def opinion(self, value: str) -> "DomainObjectBuilder": ...
    def explanation(self, value: str) -> "DomainObjectBuilder": ...
    def report_types(self, value: list[str]) -> "DomainObjectBuilder": ...
    def published(self, value: str) -> "DomainObjectBuilder": ...
    def sophistication(self, value: str) -> "DomainObjectBuilder": ...
    def targeted_sectors(self, value: list[object]) -> "DomainObjectBuilder": ...
    def tool_types(self, value: list[str]) -> "DomainObjectBuilder": ...
    def build(self) -> object: ...

class CyberObjectBuilder:
    def __init__(self, object_type: str): ...
    def mime_type(self, value: str) -> "CyberObjectBuilder": ...
    def payload_bin(self, value: str) -> "CyberObjectBuilder": ...
    def url(self, value: str) -> "CyberObjectBuilder": ...
    def hashes(self, value: object) -> "CyberObjectBuilder": ...
    def number(self, value: int) -> "CyberObjectBuilder": ...
    def value(self, value: str) -> "CyberObjectBuilder": ...
    def name(self, value: str) -> "CyberObjectBuilder": ...
    def size(self, value: int) -> "CyberObjectBuilder": ...
    def md5(self, value: str) -> "CyberObjectBuilder": ...
    def sha1(self, value: str) -> "CyberObjectBuilder": ...
    def sha256(self, value: str) -> "CyberObjectBuilder": ...
    def src_ref(self, value: str) -> "CyberObjectBuilder": ...
    def dst_ref(self, value: str) -> "CyberObjectBuilder": ...
    def protocols(self, value: list[str]) -> "CyberObjectBuilder": ...
    def pid(self, value: int) -> "CyberObjectBuilder": ...
    def vendor(self, value: str) -> "CyberObjectBuilder": ...
    def serial_number(self, value: str) -> "CyberObjectBuilder": ...
    def signature_algorithm(self, value: str) -> "CyberObjectBuilder": ...
    def issuer(self, value: str) -> "CyberObjectBuilder": ...
    def subject(self, value: str) -> "CyberObjectBuilder": ...
    def subject_public_key_algorithm(self, value: str) -> "CyberObjectBuilder": ...
    def validity_not_before(self, value: str) -> "CyberObjectBuilder": ...
    def validity_not_after(self, value: str) -> "CyberObjectBuilder": ...
    def is_multipart(self, value: bool) -> "CyberObjectBuilder": ...
    def build(self) -> object: ...

class RelationshipBuilder:
    def __init__(self): ...
    def relationship_type(self, value: str) -> "RelationshipBuilder": ...
    def source_ref(self, value: str) -> "RelationshipBuilder": ...
    def target_ref(self, value: str) -> "RelationshipBuilder": ...
    def build(self) -> object: ...

class SightingBuilder:
    def __init__(self): ...
    def sighting_of_ref(self, value: str) -> "SightingBuilder": ...
    def first_seen(self, value: str) -> "SightingBuilder": ...
    def last_seen(self, value: str) -> "SightingBuilder": ...
    def count(self, value: int) -> "SightingBuilder": ...
    def build(self) -> object: ...

class MarkingDefinitionBuilder:
    def __init__(self): ...
    def marking_type(self, value: str) -> "MarkingDefinitionBuilder": ...
    def statement(self, value: str) -> "MarkingDefinitionBuilder": ...
    def name(self, value: str) -> "MarkingDefinitionBuilder": ...
    def build(self) -> object: ...

class ExtensionDefinitionBuilder:
    def __init__(self): ...
    def name(self, value: str) -> "ExtensionDefinitionBuilder": ...
    def schema(self, value: object) -> "ExtensionDefinitionBuilder": ...
    def version(self, value: str) -> "ExtensionDefinitionBuilder": ...
    def build(self) -> object: ...

class LanguageContentBuilder:
    def __init__(self): ...
    def object_ref(self, value: str) -> "LanguageContentBuilder": ...
    def object_modified(self, value: str) -> "LanguageContentBuilder": ...
    def insert_content(self, lang: str, content: object) -> "LanguageContentBuilder": ...
    def build(self) -> object: ...

class BundleBuilder:
    def __init__(self): ...
    def add_object(self, obj: object) -> "BundleBuilder": ...
    def build(self) -> object: ...

class Hashes:
    def __init__(self): ...
    def md5(self, value: str) -> "Hashes": ...
    def sha1(self, value: str) -> "Hashes": ...
    def sha256(self, value: str) -> "Hashes": ...
    def build(self) -> object: ...
