# stixflayer — Type stubs for the Rust-compiled extension module
#
# This file describes the public API of stixflayer.stixflayer (the compiled
# .so).  The __init__.pyi in this package re-exports everything for
# `import stixflayer` ergonomics.
#
# Property declarations mirror the fixture corpus in testdata/stix/valid/.
# Every object also supports dynamic property access via __getattr__
# (unknown attributes raise AttributeError); the per-class declarations
# below exist for editor/type-checker ergonomics on the common fields.

from typing import Any, Self

# =============================================================================
# Module-level functions
# =============================================================================

def version() -> str: ...
def test_stix() -> str: ...
def create_timestamp(value: str) -> str: ...
def validate_pattern(pattern: str) -> None: ...

# =============================================================================
# Vocabulary enums
# =============================================================================

class _VocabEnum:
    def __init__(self, value: str) -> None: ...
    def value(self) -> str: ...
    @staticmethod
    def values() -> list[str]: ...
    @staticmethod
    def is_valid(value: str) -> bool: ...

class AttackMotivation(_VocabEnum): ...
class IdentitySectors(_VocabEnum): ...
class ThreatActorType(_VocabEnum): ...
class MalwareType(_VocabEnum): ...
class IndicatorType(_VocabEnum): ...
class ReportType(_VocabEnum): ...
class AttackResourceLevel(_VocabEnum): ...
class ThreatActorSophistication(_VocabEnum): ...

# =============================================================================
# STIX Domain Objects (SDOs)
# =============================================================================

class _SdoBase:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        strict: bool = True,
        version: str = "2.1",
        allow_custom: bool = False,
    ) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def spec_version(self) -> str: ...
    @property
    def created(self) -> str: ...
    @property
    def modified(self) -> str: ...
    @property
    def revoked(self) -> bool | None: ...
    def __getattr__(self, name: str) -> Any: ...

class AttackPattern(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def kill_chain_phases(self) -> list[dict[str, Any]] | None: ...

class Campaign(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def first_seen(self) -> str | None: ...
    @property
    def last_seen(self) -> str | None: ...
    @property
    def objective(self) -> str | None: ...

class CourseOfAction(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...

class Grouping(_SdoBase):
    @property
    def context(self) -> str: ...
    @property
    def object_refs(self) -> list[str]: ...
    @property
    def name(self) -> str | None: ...

class Identity(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def roles(self) -> list[str] | None: ...
    @property
    def identity_class(self) -> str | None: ...
    @property
    def sectors(self) -> list[str] | None: ...
    @property
    def contact_information(self) -> str | None: ...

class Incident(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...

class Indicator(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def indicator_types(self) -> list[str] | None: ...
    @property
    def pattern(self) -> str: ...
    @property
    def pattern_type(self) -> str: ...
    @property
    def pattern_version(self) -> str | None: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str | None: ...
    @property
    def kill_chain_phases(self) -> list[dict[str, Any]] | None: ...

class Infrastructure(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def infrastructure_types(self) -> list[str] | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def first_seen(self) -> str | None: ...
    @property
    def last_seen(self) -> str | None: ...

class IntrusionSet(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def first_seen(self) -> str | None: ...
    @property
    def last_seen(self) -> str | None: ...
    @property
    def goals(self) -> list[str] | None: ...
    @property
    def resource_level(self) -> str | None: ...
    @property
    def primary_motivation(self) -> str | None: ...
    @property
    def secondary_motivations(self) -> list[str] | None: ...

class Location(_SdoBase):
    @property
    def name(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def latitude(self) -> float | None: ...
    @property
    def longitude(self) -> float | None: ...
    @property
    def precision(self) -> float | None: ...
    @property
    def region(self) -> str | None: ...
    @property
    def country(self) -> str | None: ...

class Malware(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def malware_types(self) -> list[str] | None: ...
    @property
    def is_family(self) -> bool: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def first_seen(self) -> str | None: ...
    @property
    def last_seen(self) -> str | None: ...
    @property
    def operating_system_refs(self) -> list[str] | None: ...
    @property
    def architecture_execution_envs(self) -> list[str] | None: ...
    @property
    def implementation_languages(self) -> list[str] | None: ...
    @property
    def capabilities(self) -> list[str] | None: ...
    @property
    def sample_refs(self) -> list[str] | None: ...

class MalwareAnalysis(_SdoBase):
    @property
    def product(self) -> str: ...
    @property
    def version(self) -> str | None: ...
    @property
    def configuration_version(self) -> str | None: ...
    @property
    def modules(self) -> list[str] | None: ...
    @property
    def analysis_engine_version(self) -> str | None: ...
    @property
    def analysis_definition_version(self) -> str | None: ...
    @property
    def submitted(self) -> str | None: ...
    @property
    def analysis_started(self) -> str | None: ...
    @property
    def analysis_ended(self) -> str | None: ...
    @property
    def result_name(self) -> str | None: ...
    @property
    def result(self) -> str | None: ...

class Note(_SdoBase):
    @property
    def abstract(self) -> str | None: ...
    @property
    def content(self) -> str: ...
    @property
    def object_refs(self) -> list[str]: ...

class ObservedData(_SdoBase):
    @property
    def first_observed(self) -> str: ...
    @property
    def last_observed(self) -> str: ...
    @property
    def number_observed(self) -> int: ...
    @property
    def object_refs(self) -> list[str]: ...

class Opinion(_SdoBase):
    @property
    def opinion(self) -> str: ...
    @property
    def explanation(self) -> str | None: ...
    @property
    def object_refs(self) -> list[str]: ...

class Report(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def report_types(self) -> list[str] | None: ...
    @property
    def published(self) -> str: ...
    @property
    def object_refs(self) -> list[str]: ...

class ThreatActor(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def roles(self) -> list[str] | None: ...
    @property
    def sophistication(self) -> str | None: ...
    @property
    def resource_level(self) -> str | None: ...
    @property
    def primary_motivation(self) -> str | None: ...

class Tool(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def tool_types(self) -> list[str] | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def kill_chain_phases(self) -> list[dict[str, Any]] | None: ...

class Vulnerability(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...

# =============================================================================
# STIX Cyber Observable Objects (SCOs)
# =============================================================================

class _ScoBase:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        strict: bool = True,
        version: str = "2.1",
        allow_custom: bool = False,
    ) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def spec_version(self) -> str: ...
    def __getattr__(self, name: str) -> Any: ...

class IPv4Address(_ScoBase):
    @property
    def value(self) -> str: ...
    @property
    def resolves_to_refs(self) -> list[str] | None: ...

class IPv6Address(_ScoBase):
    @property
    def value(self) -> str: ...
    @property
    def resolves_to_refs(self) -> list[str] | None: ...

class DomainName(_ScoBase):
    @property
    def value(self) -> str: ...
    @property
    def resolves_to_refs(self) -> list[str] | None: ...

class URL(_ScoBase):
    @property
    def value(self) -> str: ...

class EmailAddress(_ScoBase):
    @property
    def value(self) -> str: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def belongs_to_ref(self) -> str | None: ...

class EmailMessage(_ScoBase):
    @property
    def is_multipart(self) -> bool | None: ...
    @property
    def subject(self) -> str | None: ...
    @property
    def body(self) -> str | None: ...
    @property
    def from_ref(self) -> str | None: ...
    @property
    def to_refs(self) -> list[str] | None: ...

class MacAddr(_ScoBase):
    @property
    def value(self) -> str: ...

class AutonomousSystem(_ScoBase):
    @property
    def number(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def rir(self) -> str | None: ...

class File(_ScoBase):
    @property
    def name(self) -> str | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def magic_number_hex(self) -> str | None: ...
    @property
    def mime_type(self) -> str | None: ...

class Software(_ScoBase):
    @property
    def name(self) -> str: ...
    @property
    def vendor(self) -> str | None: ...
    @property
    def version(self) -> str | None: ...

class Directory(_ScoBase):
    @property
    def path(self) -> str: ...
    @property
    def path_enc(self) -> str | None: ...
    @property
    def ctime(self) -> str | None: ...
    @property
    def mtime(self) -> str | None: ...

class Mutex(_ScoBase):
    @property
    def name(self) -> str: ...

class Process(_ScoBase):
    @property
    def name(self) -> str | None: ...
    @property
    def pid(self) -> int | None: ...
    @property
    def parent_ref(self) -> str | None: ...
    @property
    def creator_user_ref(self) -> str | None: ...

class NetworkTraffic(_ScoBase):
    @property
    def src_ref(self) -> str | None: ...
    @property
    def dst_ref(self) -> str | None: ...
    @property
    def src_port(self) -> int | None: ...
    @property
    def dst_port(self) -> int | None: ...
    @property
    def protocols(self) -> list[str]: ...
    @property
    def extensions(self) -> dict[str, Any] | None: ...

class UserAccount(_ScoBase):
    @property
    def account_type(self) -> str | None: ...
    @property
    def user_id(self) -> str | None: ...
    @property
    def account_login(self) -> str | None: ...
    @property
    def credential_type(self) -> str | None: ...

class WindowsRegistryKey(_ScoBase):
    @property
    def key(self) -> str: ...
    @property
    def values(self) -> list[dict[str, Any]] | None: ...

class X509Certificate(_ScoBase):
    @property
    def serial_number(self) -> str | None: ...
    @property
    def signature_algorithm(self) -> str | None: ...
    @property
    def issuer(self) -> str | None: ...
    @property
    def subject(self) -> str | None: ...
    @property
    def subject_public_key_algorithm(self) -> str | None: ...
    @property
    def x509_v3_extensions(self) -> dict[str, Any] | None: ...

class Artifact(_ScoBase):
    @property
    def mime_type(self) -> str | None: ...
    @property
    def payload_bin(self) -> str | None: ...

# =============================================================================
# STIX Relationship Objects (SROs)
# =============================================================================

class Relationship(_SdoBase):
    @property
    def relationship_type(self) -> str: ...
    @property
    def source_ref(self) -> str: ...
    @property
    def target_ref(self) -> str: ...
    @property
    def description(self) -> str | None: ...

class Sighting(_SdoBase):
    @property
    def sighting_of_ref(self) -> str: ...
    @property
    def first_seen(self) -> str | None: ...
    @property
    def last_seen(self) -> str | None: ...
    @property
    def count(self) -> int | None: ...

# =============================================================================
# Meta Objects
# =============================================================================

class MarkingDefinition(_SdoBase):
    @property
    def name(self) -> str | None: ...
    @property
    def definition_type(self) -> str: ...
    @property
    def definition(self) -> dict[str, Any]: ...

class ExtensionDefinition(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def schema(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def extension_types(self) -> list[str]: ...
    @property
    def extension_properties(self) -> list[str] | None: ...
    @property
    def created_by_ref(self) -> str: ...

class LanguageContent(_SdoBase):
    def insert_content_strings(self, lang: str, content: dict[str, str]) -> None: ...
    def insert_content_lists(self, lang: str, content: dict[str, list[str]]) -> None: ...
    def insert_content_objects(
        self, lang: str, content: dict[str, dict[str, str | list[str]]]
    ) -> None: ...
    @property
    def object_ref(self) -> str: ...
    @property
    def object_modified(self) -> str: ...
    @property
    def contents(self) -> dict[str, Any]: ...

class CustomObject:
    def __init__(
        self,
        type_: str,
        extension_type: str,
        custom_properties_json: str,
        extension_definition_id: str | None = None,
    ) -> None: ...
    @classmethod
    def from_json(cls, json_str: str) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def custom_properties(self) -> str: ...

# =============================================================================
# Bundle
# =============================================================================

class Bundle:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(cls, json_str: str) -> Self: ...
    def to_json(self) -> str: ...
    def add(self, stix_json: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def object_count(self) -> int: ...
    @property
    def type(self) -> str: ...
