# stixflayer — Type stubs for the Rust-compiled extension module
#
# This file describes the public API of stixflayer.stixflayer (the compiled
# .so).  The __init__.pyi in this package re-exports everything for
# `import stixflayer` ergonomics.

from typing import Any, Self

# =============================================================================
# Module-level functions
# =============================================================================

def version() -> str: ...
def test_stix() -> str: ...
def create_timestamp(value: str) -> str: ...
def validate_pattern(pattern: str) -> None: ...

# =============================================================================
# Vocabulary enums
# =============================================================================

class _VocabEnum:
    def __init__(self, value: str) -> None: ...
    def value(self) -> str: ...
    @staticmethod
    def values() -> list[str]: ...
    @staticmethod
    def is_valid(value: str) -> bool: ...

class AttackMotivation(_VocabEnum): ...
class IdentitySectors(_VocabEnum): ...
class ThreatActorType(_VocabEnum): ...
class MalwareType(_VocabEnum): ...
class IndicatorType(_VocabEnum): ...
class ReportType(_VocabEnum): ...
class AttackResourceLevel(_VocabEnum): ...
class ThreatActorSophistication(_VocabEnum): ...

# =============================================================================
# STIX Domain Objects (SDOs)
# =============================================================================

class _SdoBase:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        strict: bool = True,
        version: str = "2.1",
        allow_custom: bool = False,
    ) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...
    def __getattr__(self, name: str) -> Any: ...

class AttackPattern(_SdoBase):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def aliases(self) -> list[str] | None: ...
    @property
    def kill_chain_phases(self) -> list[dict[str, Any]] | None: ...

class Campaign(_SdoBase): ...
class CourseOfAction(_SdoBase): ...
class Grouping(_SdoBase): ...
class Identity(_SdoBase): ...
class Incident(_SdoBase): ...
class Infrastructure(_SdoBase): ...
class IntrusionSet(_SdoBase): ...
class Location(_SdoBase): ...
class Malware(_SdoBase): ...
class MalwareAnalysis(_SdoBase): ...
class Note(_SdoBase): ...
class ObservedData(_SdoBase): ...
class Opinion(_SdoBase): ...
class Report(_SdoBase): ...
class ThreatActor(_SdoBase): ...
class Tool(_SdoBase): ...
class Vulnerability(_SdoBase): ...
class Indicator(_SdoBase): ...

# =============================================================================
# STIX Cyber Observable Objects (SCOs)
# =============================================================================

class _ScoBase:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        strict: bool = True,
        version: str = "2.1",
        allow_custom: bool = False,
    ) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...

class IPv4Address(_ScoBase):
    @property
    def value(self) -> str: ...

class IPv6Address(_ScoBase):
    @property
    def value(self) -> str: ...

class DomainName(_ScoBase):
    @property
    def value(self) -> str: ...

class URL(_ScoBase):
    @property
    def value(self) -> str: ...

class EmailAddress(_ScoBase):
    @property
    def value(self) -> str: ...

class EmailMessage(_ScoBase):
    @property
    def from_ref(self) -> str: ...

class MacAddr(_ScoBase):
    @property
    def value(self) -> str: ...

class AutonomousSystem(_ScoBase):
    @property
    def number(self) -> int: ...

class File(_ScoBase):
    @property
    def name(self) -> str: ...

class Software(_ScoBase):
    @property
    def name(self) -> str: ...

class Directory(_ScoBase):
    @property
    def path(self) -> str: ...

class Mutex(_ScoBase):
    @property
    def name(self) -> str: ...

class Process(_ScoBase): ...
class NetworkTraffic(_ScoBase): ...

class UserAccount(_ScoBase):
    @property
    def account_login(self) -> str: ...

class WindowsRegistryKey(_ScoBase):
    @property
    def key(self) -> str: ...

class X509Certificate(_ScoBase):
    @property
    def serial_number(self) -> str: ...

class Artifact(_ScoBase):
    @property
    def mime_type(self) -> str: ...

# =============================================================================
# STIX Relationship Objects (SROs)
# =============================================================================

class Relationship(_SdoBase): ...
class Sighting(_SdoBase): ...

# =============================================================================
# Meta Objects
# =============================================================================

class MarkingDefinition(_SdoBase): ...
class ExtensionDefinition(_SdoBase): ...

class LanguageContent(_SdoBase):
    def insert_content_strings(self, lang: str, content: dict[str, str]) -> None: ...
    def insert_content_lists(self, lang: str, content: dict[str, list[str]]) -> None: ...
    def insert_content_objects(
        self, lang: str, content: dict[str, dict[str, str | list[str]]]
    ) -> None: ...
    @property
    def object_ref(self) -> str: ...

class CustomObject:
    def __init__(
        self,
        type_: str,
        extension_type: str,
        custom_properties_json: str,
        extension_definition_id: str | None = None,
    ) -> None: ...
    @classmethod
    def from_json(cls, json_str: str) -> Self: ...
    def to_json(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def custom_properties(self) -> str: ...

# =============================================================================
# Bundle
# =============================================================================

class Bundle:
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(cls, json_str: str) -> Self: ...
    def to_json(self) -> str: ...
    def add(self, stix_json: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def object_count(self) -> int: ...
    @property
    def type(self) -> str: ...
